apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-foo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://github.com/tianwg/lesson.git
    targetRevision: HEAD
    path: environments/dev/app-foo
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=fase
      - Validate=true
      - Prunepropagationpolicy=Foreground
      - Prune=true
